// Generated by gencpp from file assignment/calc_serviceResponse.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT_MESSAGE_CALC_SERVICERESPONSE_H
#define ASSIGNMENT_MESSAGE_CALC_SERVICERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assignment
{
template <class ContainerAllocator>
struct calc_serviceResponse_
{
  typedef calc_serviceResponse_<ContainerAllocator> Type;

  calc_serviceResponse_()
    : result(0.0)  {
    }
  calc_serviceResponse_(const ContainerAllocator& _alloc)
    : result(0.0)  {
  (void)_alloc;
    }



   typedef double _result_type;
  _result_type result;




  typedef boost::shared_ptr< ::assignment::calc_serviceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignment::calc_serviceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct calc_serviceResponse_

typedef ::assignment::calc_serviceResponse_<std::allocator<void> > calc_serviceResponse;

typedef boost::shared_ptr< ::assignment::calc_serviceResponse > calc_serviceResponsePtr;
typedef boost::shared_ptr< ::assignment::calc_serviceResponse const> calc_serviceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignment::calc_serviceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignment::calc_serviceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace assignment

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::assignment::calc_serviceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment::calc_serviceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment::calc_serviceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment::calc_serviceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment::calc_serviceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment::calc_serviceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignment::calc_serviceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "254fb2d8c4e08eff5dc6a560ed51dd52";
  }

  static const char* value(const ::assignment::calc_serviceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x254fb2d8c4e08effULL;
  static const uint64_t static_value2 = 0x5dc6a560ed51dd52ULL;
};

template<class ContainerAllocator>
struct DataType< ::assignment::calc_serviceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignment/calc_serviceResponse";
  }

  static const char* value(const ::assignment::calc_serviceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignment::calc_serviceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 result\n\
";
  }

  static const char* value(const ::assignment::calc_serviceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignment::calc_serviceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct calc_serviceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignment::calc_serviceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignment::calc_serviceResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<double>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENT_MESSAGE_CALC_SERVICERESPONSE_H
