// Generated by gencpp from file assignment/calc_service.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT_MESSAGE_CALC_SERVICE_H
#define ASSIGNMENT_MESSAGE_CALC_SERVICE_H

#include <ros/service_traits.h>


#include <assignment/calc_serviceRequest.h>
#include <assignment/calc_serviceResponse.h>


namespace assignment
{

struct calc_service
{

typedef calc_serviceRequest Request;
typedef calc_serviceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct calc_service
} // namespace assignment


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::assignment::calc_service > {
  static const char* value()
  {
    return "28b1b2ea728b368b3d6cf927afcd1305";
  }

  static const char* value(const ::assignment::calc_service&) { return value(); }
};

template<>
struct DataType< ::assignment::calc_service > {
  static const char* value()
  {
    return "assignment/calc_service";
  }

  static const char* value(const ::assignment::calc_service&) { return value(); }
};


// service_traits::MD5Sum< ::assignment::calc_serviceRequest> should match 
// service_traits::MD5Sum< ::assignment::calc_service > 
template<>
struct MD5Sum< ::assignment::calc_serviceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::assignment::calc_service >::value();
  }
  static const char* value(const ::assignment::calc_serviceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignment::calc_serviceRequest> should match 
// service_traits::DataType< ::assignment::calc_service > 
template<>
struct DataType< ::assignment::calc_serviceRequest>
{
  static const char* value()
  {
    return DataType< ::assignment::calc_service >::value();
  }
  static const char* value(const ::assignment::calc_serviceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::assignment::calc_serviceResponse> should match 
// service_traits::MD5Sum< ::assignment::calc_service > 
template<>
struct MD5Sum< ::assignment::calc_serviceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::assignment::calc_service >::value();
  }
  static const char* value(const ::assignment::calc_serviceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignment::calc_serviceResponse> should match 
// service_traits::DataType< ::assignment::calc_service > 
template<>
struct DataType< ::assignment::calc_serviceResponse>
{
  static const char* value()
  {
    return DataType< ::assignment::calc_service >::value();
  }
  static const char* value(const ::assignment::calc_serviceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASSIGNMENT_MESSAGE_CALC_SERVICE_H
