// Generated by gencpp from file asimov_tasks_package/calc_service.msg
// DO NOT EDIT!


#ifndef ASIMOV_TASKS_PACKAGE_MESSAGE_CALC_SERVICE_H
#define ASIMOV_TASKS_PACKAGE_MESSAGE_CALC_SERVICE_H

#include <ros/service_traits.h>


#include <asimov_tasks_package/calc_serviceRequest.h>
#include <asimov_tasks_package/calc_serviceResponse.h>


namespace asimov_tasks_package
{

struct calc_service
{

typedef calc_serviceRequest Request;
typedef calc_serviceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct calc_service
} // namespace asimov_tasks_package


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::asimov_tasks_package::calc_service > {
  static const char* value()
  {
    return "1b84c9a3d2a8829a1c1fff193adfda10";
  }

  static const char* value(const ::asimov_tasks_package::calc_service&) { return value(); }
};

template<>
struct DataType< ::asimov_tasks_package::calc_service > {
  static const char* value()
  {
    return "asimov_tasks_package/calc_service";
  }

  static const char* value(const ::asimov_tasks_package::calc_service&) { return value(); }
};


// service_traits::MD5Sum< ::asimov_tasks_package::calc_serviceRequest> should match 
// service_traits::MD5Sum< ::asimov_tasks_package::calc_service > 
template<>
struct MD5Sum< ::asimov_tasks_package::calc_serviceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::asimov_tasks_package::calc_service >::value();
  }
  static const char* value(const ::asimov_tasks_package::calc_serviceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::asimov_tasks_package::calc_serviceRequest> should match 
// service_traits::DataType< ::asimov_tasks_package::calc_service > 
template<>
struct DataType< ::asimov_tasks_package::calc_serviceRequest>
{
  static const char* value()
  {
    return DataType< ::asimov_tasks_package::calc_service >::value();
  }
  static const char* value(const ::asimov_tasks_package::calc_serviceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::asimov_tasks_package::calc_serviceResponse> should match 
// service_traits::MD5Sum< ::asimov_tasks_package::calc_service > 
template<>
struct MD5Sum< ::asimov_tasks_package::calc_serviceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::asimov_tasks_package::calc_service >::value();
  }
  static const char* value(const ::asimov_tasks_package::calc_serviceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::asimov_tasks_package::calc_serviceResponse> should match 
// service_traits::DataType< ::asimov_tasks_package::calc_service > 
template<>
struct DataType< ::asimov_tasks_package::calc_serviceResponse>
{
  static const char* value()
  {
    return DataType< ::asimov_tasks_package::calc_service >::value();
  }
  static const char* value(const ::asimov_tasks_package::calc_serviceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASIMOV_TASKS_PACKAGE_MESSAGE_CALC_SERVICE_H
