// Generated by gencpp from file asimov_tasks_package/calc_message.msg
// DO NOT EDIT!


#ifndef ASIMOV_TASKS_PACKAGE_MESSAGE_CALC_MESSAGE_H
#define ASIMOV_TASKS_PACKAGE_MESSAGE_CALC_MESSAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace asimov_tasks_package
{
template <class ContainerAllocator>
struct calc_message_
{
  typedef calc_message_<ContainerAllocator> Type;

  calc_message_()
    {
    }
  calc_message_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::asimov_tasks_package::calc_message_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::asimov_tasks_package::calc_message_<ContainerAllocator> const> ConstPtr;

}; // struct calc_message_

typedef ::asimov_tasks_package::calc_message_<std::allocator<void> > calc_message;

typedef boost::shared_ptr< ::asimov_tasks_package::calc_message > calc_messagePtr;
typedef boost::shared_ptr< ::asimov_tasks_package::calc_message const> calc_messageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::asimov_tasks_package::calc_message_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::asimov_tasks_package::calc_message_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace asimov_tasks_package

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'asimov_tasks_package': ['/home/rajesh/ROS_GIT_Workspace/ROS_Projects/src/asimov_tasks_package/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::asimov_tasks_package::calc_message_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::asimov_tasks_package::calc_message_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::asimov_tasks_package::calc_message_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::asimov_tasks_package::calc_message_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::asimov_tasks_package::calc_message_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::asimov_tasks_package::calc_message_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::asimov_tasks_package::calc_message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::asimov_tasks_package::calc_message_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::asimov_tasks_package::calc_message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "asimov_tasks_package/calc_message";
  }

  static const char* value(const ::asimov_tasks_package::calc_message_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::asimov_tasks_package::calc_message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::asimov_tasks_package::calc_message_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::asimov_tasks_package::calc_message_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct calc_message_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::asimov_tasks_package::calc_message_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::asimov_tasks_package::calc_message_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ASIMOV_TASKS_PACKAGE_MESSAGE_CALC_MESSAGE_H
